// Ping Island managed integration: opencode-hooks
// Generated by Ping Island. Reinstall from Island settings if you need to refresh it.

const BRIDGE_ARGS = ["\/Users\/youkipepper\/.ping-island\/bin\/ping-island-bridge","--source","claude","--client-kind","opencode","--client-name","OpenCode","--client-origin","cli","--client-originator","OpenCode","--thread-source","opencode-plugin"];
const ENV_KEYS = [
  "TERM_PROGRAM",
  "ITERM_SESSION_ID",
  "TERM_SESSION_ID",
  "TMUX",
  "TMUX_PANE",
  "KITTY_WINDOW_ID",
  "__CFBundleIdentifier",
  "CONDUCTOR_WORKSPACE_NAME",
  "CONDUCTOR_PORT",
  "CURSOR_TRACE_ID",
  "CMUX_WORKSPACE_ID",
  "CMUX_SURFACE_ID",
  "CMUX_SOCKET_PATH",
  "WINDOWSERVER_DISPLAY_UUID"
];

function isObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function atPath(value, path) {
  let current = value;
  for (const key of path) {
    if (!isObject(current) && !Array.isArray(current)) return undefined;
    current = current?.[key];
  }
  return current;
}

function firstDefined(value, paths) {
  for (const path of paths) {
    const candidate = atPath(value, path);
    if (candidate !== undefined && candidate !== null && candidate !== "") {
      return candidate;
    }
  }
  return undefined;
}

function firstString(value, keys, depth = 0) {
  if (depth > 5 || value == null) return undefined;
  if (typeof value === "string" && value.trim().length > 0) return value;
  if (Array.isArray(value)) {
    for (const entry of value) {
      const found = firstString(entry, keys, depth + 1);
      if (found) return found;
    }
    return undefined;
  }
  if (!isObject(value)) return undefined;

  for (const key of keys) {
    const candidate = value[key];
    if (typeof candidate === "string" && candidate.trim().length > 0) {
      return candidate;
    }
  }

  for (const nested of Object.values(value)) {
    const found = firstString(nested, keys, depth + 1);
    if (found) return found;
  }
  return undefined;
}

function firstObject(value, keys, depth = 0) {
  if (depth > 5 || value == null) return undefined;
  if (Array.isArray(value)) {
    for (const entry of value) {
      const found = firstObject(entry, keys, depth + 1);
      if (found) return found;
    }
    return undefined;
  }
  if (!isObject(value)) return undefined;

  for (const key of keys) {
    const candidate = value[key];
    if (isObject(candidate) || Array.isArray(candidate)) {
      return candidate;
    }
  }

  for (const nested of Object.values(value)) {
    const found = firstObject(nested, keys, depth + 1);
    if (found) return found;
  }
  return undefined;
}

function stableString(value) {
  if (value == null) return undefined;
  if (typeof value === "string") {
    const trimmed = value.trim();
    return trimmed.length > 0 ? trimmed : undefined;
  }
  try {
    return JSON.stringify(value);
  } catch {
    return undefined;
  }
}

function capitalize(value) {
  if (typeof value !== "string" || value.length === 0) return undefined;
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function collectBridgeEnv() {
  const collected = {};
  for (const key of ENV_KEYS) {
    const value = process.env[key];
    if (typeof value === "string" && value.length > 0) {
      collected[key] = value;
    }
  }
  return collected;
}

function detectTTY() {
  try {
    const { execSync } = require("child_process");
    let walkPid = process.pid;
    for (let index = 0; index < 8; index += 1) {
      const info = execSync(`ps -o tty=,ppid= -p ${walkPid}`, { timeout: 1000 })
        .toString()
        .trim();
      if (!info) break;
      const parts = info.split(/\s+/);
      const tty = parts[0];
      const ppid = Number.parseInt(parts[1] || "", 10);
      if (tty && tty !== "??" && tty !== "?") {
        return tty.startsWith("/dev/") ? tty : `/dev/${tty}`;
      }
      if (!Number.isFinite(ppid) || ppid <= 1) break;
      walkPid = ppid;
    }
  } catch {
    return undefined;
  }
  return undefined;
}

function makeBasePayload(sessionId, extra = {}) {
  return {
    session_id: sessionId,
    _source: "opencode",
    _env: collectBridgeEnv(),
    _tty: detectedTTY,
    pid: process.pid,
    ...extra
  };
}

function normalizeQuestions(questions) {
  if (!Array.isArray(questions)) return [];
  return questions.map((question) => ({
    id: stableString(question?.id),
    header: stableString(question?.header),
    question: stableString(question?.question),
    description: stableString(question?.description),
    options: Array.isArray(question?.options)
      ? question.options
          .map((option) => {
            if (typeof option === "string") return option;
            if (!isObject(option)) return undefined;
            const label = stableString(option.label);
            if (!label) return undefined;
            return {
              label,
              description: stableString(option.description)
            };
          })
          .filter(Boolean)
      : [],
    multiple: question?.multiple === true
  })).filter((question) => question.question);
}

function questionAnswerArrays(questions, answers) {
  if (!isObject(answers)) return [];
  const mappedAnswers = questions
    .map((question, index) => {
      const lookupKeys = [
        stableString(question.id),
        stableString(question.question),
        stableString(question.header),
        String(index)
      ].filter(Boolean);

      const value = lookupKeys
        .map((key) => answers[key])
        .find((candidate) => candidate !== undefined && candidate !== null);
      if (value === undefined || value === null) return [];

      if (Array.isArray(value)) {
        return value
          .map((entry) => stableString(entry))
          .filter(Boolean);
      }

      const normalized = stableString(value);
      return normalized ? [normalized] : [];
    })
    .filter((entry) => entry.length > 0);

  if (mappedAnswers.length > 0) return mappedAnswers;
  return Object.values(answers)
    .map((value) => {
      if (Array.isArray(value)) {
        return value
          .map((entry) => stableString(entry))
          .filter(Boolean);
      }
      const normalized = stableString(value);
      return normalized ? [normalized] : [];
    })
    .filter((entry) => entry.length > 0);
}

function toolNameForPermission(permission) {
  if (permission === "bash") return "Bash";
  if (permission === "edit" || permission === "write") return "Write";
  return capitalize(permission) ?? "Permission";
}

function permissionToolInput(properties) {
  const patterns = Array.isArray(properties?.patterns)
    ? properties.patterns.map((entry) => stableString(entry)).filter(Boolean)
    : [];
  const input = {};
  if (patterns.length > 0) {
    input.patterns = patterns;
  }
  if (isObject(properties?.metadata)) {
    input.metadata = properties.metadata;
  }
  if (properties?.permission === "bash" && patterns.length > 0) {
    input.command = patterns.join(" && ");
  }
  if ((properties?.permission === "edit" || properties?.permission === "write") && patterns.length > 0) {
    input.file_path = patterns[0];
  }
  return Object.keys(input).length > 0 ? input : undefined;
}

function mapEvent(event) {
  const type = event?.type;
  const properties = isObject(event?.properties) ? event.properties : {};
  if (typeof type !== "string" || type.length === 0) return undefined;

  if (type === "session.created" && isObject(properties.info) && stableString(properties.info.id)) {
    const rawSessionID = stableString(properties.info.id);
    const cwd = stableString(properties.info.directory);
    const sessionId = `opencode-${rawSessionID}`;
    const session = getSession(rawSessionID);
    session.cwd = cwd;
    return makeBasePayload(sessionId, {
      hook_event_name: "SessionStart",
      cwd
    });
  }

  if (type === "session.deleted" && isObject(properties.info) && stableString(properties.info.id)) {
    const rawSessionID = stableString(properties.info.id);
    sessions.delete(rawSessionID);
    messageRoles.forEach((value, key) => {
      if (value?.sessionID === rawSessionID) {
        messageRoles.delete(key);
      }
    });
    return makeBasePayload(`opencode-${rawSessionID}`, {
      hook_event_name: "SessionEnd"
    });
  }

  if (type === "session.updated" && isObject(properties.info) && stableString(properties.info.id)) {
    const rawSessionID = stableString(properties.info.id);
    const session = getSession(rawSessionID);
    const cwd = stableString(properties.info.directory) ?? session.cwd;
    if (cwd) session.cwd = cwd;
    const title = stableString(properties.info.title);
    if (title && !title.startsWith("New session")) {
      session.pendingTitle = title;
    }
    if (properties.info.time?.archived) {
      sessions.delete(rawSessionID);
      return makeBasePayload(`opencode-${rawSessionID}`, {
        hook_event_name: "SessionEnd",
        cwd
      });
    }
    return undefined;
  }

  if (type === "session.status" && stableString(properties.sessionID)) {
    const rawSessionID = stableString(properties.sessionID);
    const session = getSession(rawSessionID);
    if (properties.status?.type === "idle") {
      const payload = makeBasePayload(`opencode-${rawSessionID}`, {
        hook_event_name: "Stop",
        cwd: session.cwd,
        last_assistant_message: session.lastAssistantText || undefined,
        session_title: session.pendingTitle || undefined
      });
      session.pendingTitle = undefined;
      return payload;
    }
    return undefined;
  }

  if (type === "message.updated" && isObject(properties.info) && stableString(properties.info.id) && stableString(properties.info.sessionID)) {
    messageRoles.set(stableString(properties.info.id), {
      role: stableString(properties.info.role),
      sessionID: stableString(properties.info.sessionID)
    });
    if (messageRoles.size > 200) {
      messageRoles.delete(messageRoles.keys().next().value);
    }
    return undefined;
  }

  if (type === "message.part.updated" && isObject(properties.part) && stableString(properties.part.sessionID)) {
    const rawSessionID = stableString(properties.part.sessionID);
    const session = getSession(rawSessionID);
    const sessionId = `opencode-${rawSessionID}`;

    if (properties.part.type === "text" && stableString(properties.part.messageID)) {
      const meta = messageRoles.get(stableString(properties.part.messageID));
      if (!meta) return undefined;

      const text = stableString(properties.part.text);
      if (!text) return undefined;

      if (meta.role === "user") {
        session.lastUserText = text;
        return makeBasePayload(sessionId, {
          hook_event_name: "UserPromptSubmit",
          cwd: session.cwd,
          prompt: text
        });
      }

      if (meta.role === "assistant") {
        session.lastAssistantText = text;
      }
      return undefined;
    }

    if (properties.part.type === "tool") {
      const toolName = capitalize(stableString(properties.part.tool)) ?? "Tool";
      const toolInput = properties.part.state?.input;
      const state = stableString(properties.part.state?.status);
      if (state === "running" || state === "pending") {
        return makeBasePayload(sessionId, {
          hook_event_name: "PreToolUse",
          cwd: session.cwd,
          tool_name: toolName,
          tool_input: isObject(toolInput) || Array.isArray(toolInput) ? toolInput : undefined
        });
      }
      if (state === "completed" || state === "error") {
        return makeBasePayload(sessionId, {
          hook_event_name: "PostToolUse",
          cwd: session.cwd,
          tool_name: toolName,
          tool_input: isObject(toolInput) || Array.isArray(toolInput) ? toolInput : undefined
        });
      }
    }
  }

  if (type === "permission.asked" && stableString(properties.id) && stableString(properties.sessionID)) {
    const rawSessionID = stableString(properties.sessionID);
    const session = getSession(rawSessionID);
    return makeBasePayload(`opencode-${rawSessionID}`, {
      hook_event_name: "PermissionRequest",
      cwd: session.cwd,
      tool_name: toolNameForPermission(properties.permission),
      tool_input: permissionToolInput(properties),
      _opencode_request_id: stableString(properties.id)
    });
  }

  if (type === "permission.replied" && stableString(properties.sessionID)) {
    const rawSessionID = stableString(properties.sessionID);
    const session = getSession(rawSessionID);
    return makeBasePayload(`opencode-${rawSessionID}`, {
      hook_event_name: "PostToolUse",
      cwd: session.cwd,
      tool_name: toolNameForPermission(properties.permission)
    });
  }

  if (type === "question.asked" && stableString(properties.id) && stableString(properties.sessionID)) {
    const rawSessionID = stableString(properties.sessionID);
    const session = getSession(rawSessionID);
    return makeBasePayload(`opencode-${rawSessionID}`, {
      hook_event_name: "PreToolUse",
      cwd: session.cwd,
      tool_name: "AskUserQuestion",
      tool_input: { questions: normalizeQuestions(properties.questions) },
      _opencode_request_id: stableString(properties.id)
    });
  }

  if ((type === "question.replied" || type === "question.rejected") && stableString(properties.sessionID)) {
    const rawSessionID = stableString(properties.sessionID);
    const session = getSession(rawSessionID);
    return makeBasePayload(`opencode-${rawSessionID}`, {
      hook_event_name: "PostToolUse",
      cwd: session.cwd,
      tool_name: "AskUserQuestion"
    });
  }

  return undefined;
}

async function runBridge(payload, captureResponse = false) {
  const env = { ...(globalThis.process?.env ?? {}) };
  if (isObject(payload?._env)) {
    Object.assign(env, payload._env);
  }
  if (typeof payload?._tty === "string" && payload._tty.length > 0) {
    env.TTY = payload._tty;
  }

  try {
    const subprocess = Bun.spawn(BRIDGE_ARGS, {
      stdin: new Response(JSON.stringify(payload)),
      stdout: captureResponse ? "pipe" : "ignore",
      stderr: "ignore",
      env
    });

    const exitCode = await subprocess.exited;
    if (!captureResponse || exitCode !== 0 || !subprocess.stdout) {
      return null;
    }

    const stdout = (await new Response(subprocess.stdout).text()).trim();
    if (!stdout) return null;
    try {
      return JSON.parse(stdout);
    } catch {
      return null;
    }
  } catch {
    // OpenCode hooks should never fail because Island is unavailable.
    return null;
  }
}

const detectedTTY = detectTTY();
const messageRoles = new Map();
const sessions = new Map();

function getSession(sessionID) {
  if (!sessions.has(sessionID)) {
    sessions.set(sessionID, {
      cwd: undefined,
      lastUserText: "",
      lastAssistantText: "",
      pendingTitle: undefined
    });
  }
  return sessions.get(sessionID);
}

export const server = async ({ client, serverUrl }) => {
  const internalFetch = client?._client?.getConfig?.()?.fetch ?? globalThis.fetch ?? null;
  const serverPort = Number.parseInt(serverUrl?.port || "", 10) || 4096;

  return {
  name: "Ping Island",
  description: "Forward OpenCode hook events to Ping Island.",
  event: async ({ event }) => {
    const payload = mapEvent(event);
    if (!payload) return;

    const requestId = stableString(payload._opencode_request_id);
    const questions = payload.tool_input?.questions;

    if (
      payload.hook_event_name === "PreToolUse"
        && payload.tool_name === "AskUserQuestion"
        && requestId
        && internalFetch
    ) {
      const response = await runBridge(payload, true);
      const answers = response?.hookSpecificOutput?.decision?.updatedInput?.answers
        ?? response?.hookSpecificOutput?.updatedInput?.answers;
      const answerArray = questionAnswerArrays(Array.isArray(questions) ? questions : [], answers);
      if (answerArray.length === 0) return;

      try {
        await internalFetch(new Request(`http://localhost:${serverPort}/question/${requestId}/reply`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ answers: answerArray })
        }));
      } catch {
        // Ignore OpenCode reply failures so hooks never crash the session.
      }
      return;
    }

    if (payload.hook_event_name === "PermissionRequest" && requestId && internalFetch) {
      const response = await runBridge(payload, true);
      const behavior = stableString(response?.hookSpecificOutput?.decision?.behavior)
        ?? stableString(response?.hookSpecificOutput?.permissionDecision);
      const reason = stableString(response?.hookSpecificOutput?.decision?.message)
        ?? stableString(response?.hookSpecificOutput?.decision?.reason)
        ?? stableString(response?.hookSpecificOutput?.permissionDecisionReason);
      if (!behavior) return;

      const reply = behavior === "allow"
        ? "once"
        : behavior === "allow_for_session" || behavior === "always"
          ? "always"
          : "reject";

      try {
        await internalFetch(new Request(`http://localhost:${serverPort}/permission/${requestId}/reply`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ reply, message: reason })
        }));
      } catch {
        // Ignore OpenCode reply failures so hooks never crash the session.
      }
      return;
    }

    await runBridge(payload, false);
  },
  "shell.env": async (_input, output) => {
    for (const key of ENV_KEYS) {
      const value = process.env[key];
      if (typeof value === "string" && value.length > 0) {
        output.env[key] = value;
      }
    }
    if (detectedTTY) {
      output.env.TTY = detectedTTY;
    }
  }
};

};

export default server;