// vibe-island-plugin-marker — auto-generated by Vibe Island
// version: v8
// 事件转发 + 终端环境注入 + 权限审批 + 问答交互（in-process reply） + 文本提取
import { connect } from "net";

const SOCKET = "/tmp/vibe-island.sock";

function sendToSocket(json) {
  return new Promise((resolve) => {
    try {
      const sock = connect({ path: SOCKET }, () => {
        sock.write(JSON.stringify(json));
        sock.end();
        resolve(true);
      });
      sock.on("error", () => resolve(false));
      sock.setTimeout(3000, () => { sock.destroy(); resolve(false); });
    } catch { resolve(false); }
  });
}

function sendAndWaitResponse(json, timeoutMs = 300000) {
  return new Promise((resolve) => {
    try {
      const sock = connect({ path: SOCKET }, () => {
        sock.write(JSON.stringify(json));
      });
      let buf = "";
      sock.on("data", (data) => { buf += data.toString(); });
      sock.on("end", () => {
        try { resolve(JSON.parse(buf)); } catch { resolve(null); }
      });
      sock.on("error", () => resolve(null));
      sock.setTimeout(timeoutMs, () => { sock.destroy(); resolve(null); });
    } catch { resolve(null); }
  });
}

export default async ({ client, serverUrl }) => {
  const pid = process.pid;
  const serverPort = serverUrl ? parseInt(serverUrl.port) || 4096 : 4096;
  const internalFetch = client?._client?.getConfig?.()?.fetch || null;
  const msgRoles = new Map();
  const sessions = new Map();

  function getSession(sid) {
    if (!sessions.has(sid)) sessions.set(sid, { lastUserText: "", lastAssistantText: "" });
    return sessions.get(sid);
  }

  // 终端环境采集（与 Bridge EnvironmentCollector 一致）
  const ENV_KEYS = [
    "TERM_PROGRAM", "ITERM_SESSION_ID", "TERM_SESSION_ID",
    "TMUX", "TMUX_PANE", "KITTY_WINDOW_ID", "__CFBundleIdentifier",
    "CONDUCTOR_WORKSPACE_NAME", "CONDUCTOR_PORT", "CURSOR_TRACE_ID",
    "CMUX_WORKSPACE_ID", "CMUX_SURFACE_ID", "CMUX_SOCKET_PATH",
  ];
  // TTY 检测 — 沿进程树向上走（Bun worker 自身无 tty，需爬到 shell 进程）
  let detectedTty = null;
  try {
    const { execSync } = require("child_process");
    let walkPid = process.pid;
    for (let i = 0; i < 8; i++) {
      const info = execSync(`ps -o tty=,ppid= -p ${walkPid}`, { timeout: 1000 }).toString().trim();
      const parts = info.split(/\s+/);
      const tty = parts[0], ppid = parseInt(parts[1]);
      if (tty && tty !== "??" && tty !== "?") { detectedTty = `/dev/${tty}`; break; }
      if (!ppid || ppid <= 1) break;
      walkPid = ppid;
    }
  } catch {}

  function collectEnv() {
    const env = {};
    for (const k of ENV_KEYS) { if (process.env[k]) env[k] = process.env[k]; }
    return env;
  }

  // Ghostty tab 标题（OSC 2）— 与 Bridge setGhosttyTabTitle 一致
  const termProg = process.env.TERM_PROGRAM || "";
  const isOsc2Terminal = ["ghostty", "xterm-ghostty"].includes(termProg) && !process.env.TMUX;
  let displayTitle = null;

  function setTabTitle(sessionId, cwd, userText, aiTitle) {
    if (!isOsc2Terminal) return;
    const project = (cwd || process.env.PWD || "session").split("/").pop() || "session";
    const prefix = sessionId.replace("opencode-", "").slice(0, 16);
    if (aiTitle) {
      displayTitle = aiTitle.replace(/\n/g, " ").slice(0, 30);
    } else if (!displayTitle && userText) {
      displayTitle = userText.replace(/\n/g, " ").slice(0, 30);
    }
    let title;
    if (displayTitle) {
      title = `${project} · ${displayTitle} · ${prefix}`;
    } else {
      title = `${project} · ${prefix}`;
    }
    const osc = `\x1b]2;${title}\x07`;
    if (detectedTty) {
      try {
        const fs = require("fs");
        fs.writeFileSync(detectedTty, osc);
      } catch {}
    }
    try {
      const fs = require("fs");
      fs.writeFileSync(`/tmp/vibe-island-osc2-title-${prefix}`, displayTitle || "");
    } catch {}
  }

  // 公共字段：每个事件都携带，确保后启动的 Vibe Island 也能建立完整 session
  function base(sessionId, extra) {
    return { session_id: sessionId, _source: "opencode", _ppid: pid,
      _env: collectEnv(), _tty: detectedTty, _server_port: serverPort, ...extra };
  }

  const sessionCwd = new Map();

  function mapEvent(ev) {
    const t = ev.type;
    const p = ev.properties || {};

    if (t === "session.created" && p.info) {
      const cwd = p.info.directory || "";
      sessionCwd.set(p.info.id, cwd);
      return base(`opencode-${p.info.id}`, { hook_event_name: "SessionStart", cwd });
    }
    if (t === "session.deleted" && p.info) {
      sessions.delete(p.info.id); sessionCwd.delete(p.info.id);
      return base(`opencode-${p.info.id}`, { hook_event_name: "SessionEnd" });
    }
    if (t === "session.updated" && p.info) {
      if (p.info.directory) sessionCwd.set(p.info.id, p.info.directory);
      if (p.info.time?.archived) {
        sessions.delete(p.info.id); sessionCwd.delete(p.info.id);
        return base(`opencode-${p.info.id}`, { hook_event_name: "SessionEnd" });
      }
      if (p.info.title && !p.info.title.startsWith("New session")) {
        const s = getSession(p.info.id);
        s.pendingTitle = p.info.title;
        setTabTitle(`opencode-${p.info.id}`, sessionCwd.get(p.info.id), null, p.info.title);
      }
      return null;
    }
    if (t === "session.status" && p.sessionID) {
      const sid = `opencode-${p.sessionID}`;
      const s = getSession(p.sessionID);
      const cwd = sessionCwd.get(p.sessionID);
      if (p.status?.type === "idle") {
        const extra = { hook_event_name: "Stop", cwd,
          last_assistant_message: s.lastAssistantText || undefined };
        if (s.pendingTitle) { extra.codex_title = s.pendingTitle; s.pendingTitle = null; }
        return base(sid, extra);
      }
    }
    if (t === "message.updated" && p.info?.id && p.info?.sessionID) {
      msgRoles.set(p.info.id, { role: p.info.role, sessionID: p.info.sessionID });
      if (msgRoles.size > 200) { msgRoles.delete(msgRoles.keys().next().value); }
      return null;
    }
    if (t === "message.part.updated" && p.part?.type === "text" && p.part?.messageID) {
      const meta = msgRoles.get(p.part.messageID);
      if (!meta) return null;
      const s = getSession(meta.sessionID);
      const cwd = sessionCwd.get(meta.sessionID);
      const text = p.part.text || "";
      if (meta.role === "user" && text) {
        s.lastUserText = text;
        return base(`opencode-${meta.sessionID}`, {
          hook_event_name: "UserPromptSubmit", cwd, prompt: text });
      }
      if (meta.role === "assistant" && text) { s.lastAssistantText = text; }
      return null;
    }
    if (t === "message.part.updated" && p.part?.type === "tool" && p.part?.sessionID) {
      const sid = `opencode-${p.part.sessionID}`;
      const st = p.part.state?.status;
      const cwd = sessionCwd.get(p.part.sessionID);
      const toolName = (p.part.tool || "").charAt(0).toUpperCase() + (p.part.tool || "").slice(1);
      if (st === "running" || st === "pending") {
        return base(sid, { hook_event_name: "PreToolUse", cwd, tool_name: toolName,
          tool_input: p.part.state?.input || {} });
      }
      if (st === "completed" || st === "error") {
        return base(sid, { hook_event_name: "PostToolUse", cwd, tool_name: toolName });
      }
    }
    if (t === "permission.asked" && p.id && p.sessionID) {
      const toolName = (p.permission || "").charAt(0).toUpperCase() + (p.permission || "").slice(1);
      const patterns = p.patterns || [];
      const toolInput = { patterns, metadata: p.metadata };
      if (p.permission === "bash" && patterns.length > 0) {
        toolInput.command = patterns.join(" && ");
      }
      if ((p.permission === "edit" || p.permission === "write") && patterns.length > 0) {
        toolInput.file_path = patterns[0];
      }
      return base(`opencode-${p.sessionID}`, { hook_event_name: "PermissionRequest",
        cwd: sessionCwd.get(p.sessionID), tool_name: toolName,
        tool_input: toolInput,
        _opencode_request_id: p.id });
    }
    if (t === "permission.replied" && p.sessionID) {
      return base(`opencode-${p.sessionID}`, { hook_event_name: "PostToolUse",
        cwd: sessionCwd.get(p.sessionID) });
    }
    // question.asked → PermissionRequest(AskUserQuestion)：复用审批的 held connection 模式
    if (t === "question.asked" && p.id && p.sessionID) {
      const questions = (p.questions || []).map(q => ({
        question: q.question || "",
        header: q.header || "",
        options: (q.options || []).map(o => ({ label: o.label, description: o.description })),
        multiSelect: q.multiple || false,
      }));
      return base(`opencode-${p.sessionID}`, { hook_event_name: "PermissionRequest",
        cwd: sessionCwd.get(p.sessionID), tool_name: "AskUserQuestion",
        tool_input: { questions }, _opencode_request_id: p.id });
    }
    if ((t === "question.replied" || t === "question.rejected") && p.sessionID) {
      return base(`opencode-${p.sessionID}`, { hook_event_name: "PostToolUse",
        cwd: sessionCwd.get(p.sessionID) });
    }
    return null;
  }

  return {
    "event": async ({ event }) => {
      const mapped = mapEvent(event);
      if (!mapped) return;
      if (mapped.hook_event_name === "SessionStart") {
        setTabTitle(mapped.session_id, mapped.cwd, null);
      } else if (mapped.hook_event_name === "UserPromptSubmit" && mapped.prompt) {
        setTabTitle(mapped.session_id, null, mapped.prompt);
      }
      // 问答交互：同审批的 held connection 模式，回复 /question/{id}/reply
      if (mapped.hook_event_name === "PermissionRequest" && mapped.tool_name === "AskUserQuestion" && internalFetch) {
        const requestId = mapped._opencode_request_id;
        sendAndWaitResponse(mapped).then(async (response) => {
          if (!response) return;
          const answers = response?.hookSpecificOutput?.decision?.updatedInput?.answers;
          if (!answers) return;
          const qs = mapped.tool_input?.questions || [];
          const answerArray = qs.length > 0
            ? qs.map(q => answers[q.header] ? [answers[q.header]] : []).filter(a => a.length > 0)
            : Object.values(answers).map(v => [v]);
          try {
            await internalFetch(new Request(`http://localhost:${serverPort}/question/${requestId}/reply`, {
              method: "POST", headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ answers: answerArray }),
            }));
          } catch {}
        });
        return;
      }
      // 权限审批：后台 held connection 等待 Vibe Island 决定，然后 in-process 回复 OpenCode
      if (mapped.hook_event_name === "PermissionRequest" && internalFetch) {
        const requestId = mapped._opencode_request_id;
        sendAndWaitResponse(mapped).then(async (response) => {
          if (!response) return;
          const behavior = response?.hookSpecificOutput?.decision?.behavior;
          const reason = response?.hookSpecificOutput?.decision?.reason;
          if (!behavior) return;
          const reply = behavior === "allow" ? "once"
            : behavior === "always" ? "always" : "reject";
          try {
            await internalFetch(new Request(`http://localhost:${serverPort}/permission/${requestId}/reply`, {
              method: "POST", headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ reply, message: reason }),
            }));
          } catch {}
        });
        return;
      }
      await sendToSocket(mapped);
    },
    "shell.env": async (input, output) => {
      for (const v of ["TERM_PROGRAM","ITERM_SESSION_ID","TERM_SESSION_ID",
        "TMUX","TMUX_PANE","KITTY_WINDOW_ID","__CFBundleIdentifier",
        "CMUX_WORKSPACE_ID","CMUX_SURFACE_ID","CMUX_SOCKET_PATH"]) {
        if (process.env[v]) output.env["_VI_" + v] = process.env[v];
      }
    },
  };
};