[Logo-menu]
menu-button-icon-image=1
symbolic-icon=true
use-custom-icon=false

[blur-my-shell]
settings-version=2

[blur-my-shell/appfolder]
brightness=0.59999999999999998
sigma=30

[blur-my-shell/dash-to-dock]
blur=true
brightness=0.59999999999999998
sigma=30
static-blur=true
style-dash-to-dock=0

[blur-my-shell/panel]
brightness=0.59999999999999998
sigma=30

[blur-my-shell/window-list]
brightness=0.59999999999999998
sigma=30

[com-flannaghan-ProxySwitcher]
active-mode='manual'

[com/github/hermes83/compiz-windows-effect]
last-version=29
preset='R'

[dash-to-dock]
background-opacity=0.80000000000000004
dash-max-icon-size=48
dock-position='BOTTOM'
height-fraction=0.90000000000000002
multi-monitor=true
preferred-monitor=-2
preferred-monitor-by-connector='DP-2'
show-apps-at-top=true
transparency-mode='DYNAMIC'

[ding]
check-x11wayland=true
show-trash=false
show-volumes=false

[system-monitor]
show-download=false
show-upload=false
