# group|name|check|brew_type|brew|apt|dnf|pacman
cli|git|cmd:git|formula|git|git|git|git
cli|curl|cmd:curl|formula|curl|curl|curl|curl
cli|zsh|cmd:zsh|formula|zsh|zsh|zsh|zsh
cli|tmux|cmd:tmux|formula|tmux|tmux|tmux|tmux
cli|fastfetch|cmd:fastfetch|formula|fastfetch|fastfetch|fastfetch|fastfetch
cli|lazygit|cmd:lazygit|formula|lazygit|||lazygit
cli|btop|cmd:btop|formula|btop|btop|btop|btop
cli|tree|cmd:tree|formula|tree|tree|tree|tree
cli|net-tools|cmd:ifconfig|formula||net-tools|net-tools|net-tools
cli|cmatrix|cmd:cmatrix|formula|cmatrix|cmatrix|cmatrix|cmatrix
cli|starship|cmd:starship|formula|starship|starship|starship|starship
cli|lsd|cmd:lsd|formula|lsd|lsd|lsd|lsd
gui|kitty|app:Kitty|cask|kitty|kitty|kitty|kitty
gui|ghostty|app:Ghostty|cask|ghostty|||ghostty
